#!/bin/bash
#Corresponding
errCorrespond(){
	case "$1" in
		10) echo "A non-numeric input has been confirmed." ;;
		20) echo "Failed to communicate with the API" ;;
		3) echo "" ;;
	esac
}

onerror(){
	local error_code=$1
	local script=$0
	local line_num=$2
	local message=$(errCorrespond $1)
	cat - <<EOF
///////////////////////////////////////////
"Error Code : ${error_code}"
"Error Location : ${script} [Line $line]"
"Message : ${message}
///////////////////////////////////////////
EOF
}

begintrap(){
	set -e
	trap 'onerror $? $LINENO' ERR
}

begintrap
