#!/bin/bash

#Make country array
array_country=("JPY" "KRW" "USD" "EUR" \
"AUD" "CNY" "BGN" "CZK" "DKK" "GBP" "HUF" \
"PLN" "RON" "SEK" "CHF" "ISK" "NOK" "HRK" \
"RUB" "TRY" "BRL" "CAD" "HKD" "IDR" "INR" \
"MXN" "MYR" "NZD" "PHP" "SGD" "THB" "ZAR")

############################################

#Check to see if what you enter is number.
#The following sentence is used to make a numerical judgment
isnum(){
	expr "$1" + 1 >/dev/null 2>&1
	if [ "$?" -ge 2 ]; then
		if [ $(echo "$1" | tr -d [:digit:]) = '.' ]; then
			exit 
	if
	fi

	return 0

}

############################################

#Convert the entered value to a currency code
numTocode(){
#isnum $1
#if [ $? -ne 0 ]; then
#return 1
#else
	local num=$(expr "$1" - 1)
#fi


	echo ${array_country[$num]}

}
##############################################

#Get latest table
gelata(){
	ping -c -1 https://api.exchangeratesapi.io/latest?base=$1
	if [ $? -ne 0 ]; then
		exit 20
	fi	
	local table=$(curl -s https://api.exchangeratesapi.io/latest?base=$1)
	echo $table
}

#Get rate from table
rafrta(){
	echo $(gelata $1 | jq ".rates.$2")
}
##############################################

#Search Currency Correspondence Table
searchCCT(){
	vague_word=$(echo "$1" | tr [:upper:] [:lower:])
	local result=$(cat countrytable | grep "${vague_word^}")
	if [ -z "$result" ]; then
		cat countrytable | grep "[ $vague_word ]"
		printf "${BITBLIGHT}These may be close to what you want.\033[m\n"
	else
		printf "Are you referring to this, by any chance?\n${BITBLIGHT}%s\033[m\nIf so, please enter the number on the left.\n" "$result"
	fi
}

#Show all Currency Correspondence
showCCT(){
	less countrytable	
}
###############################################

#Processing user input
msgPattern(){
	RED=$(printf "\033[31m")
	BITBLIGHT=$(printf "\033[38;5;250m")
	msg_base="Choice base currency's number."
	msg_aimai="When you forget currency code, enter name of country.
	msg_more_menu="(if you want to see more, please enter 'M')"
	msg_target= "Choice target currency's number for exchange"
	if [ $# -eq 0 ]; then
		printf "${BITBLIGHT}%s\033[m\n%s\n%s\n" "$msg_base" "$msg_aimai" "$msg_more_menu"
	else
		msg_selected=$(printf "You've already chosen %s as base currency.\nChoice targert currency." "$1")
		printf "${BITBLIGHT}%s\033[m\n%s\n" "$msg_selected" "$msg_aimai"
	fi
}		
#################################################

warningMSG(){
	msg_warn=$(printf "Incorrect input has been detected.\nYou have to startb over.")
	printf "${RED}%s\033[m\n" "$msg_warn"
}

#################################################

#Processing of amounts
msgAmounts(){
	msg_amounts="How mach money are you trying exchange?"
	}





