#!/bin/bash
. MessageColor 
array_country=("JPY" "KRW" "USD" "EUR" \
"AUD" "CNY" "BGN" "CZK" "DKK" "GBP" "HUF" \
"PLN" "RON" "SEK" "CHF" "ISK" "NOK" "HRK" \
"RUB" "TRY" "BRL" "CAD" "HKD" "IDR" "INR" \
"MXN" "MYR" "NZD" "PHP" "SGD" "THB" "ZAR")
#_______________________________________#
numTocode(){
	local num=$(expr "$1" - 1 )
	echo ${array_country[$num]}
}
#_______________________________________#
searchCCT(){
	vague_word=$(echo "$1" | tr [:upper:] [:lower:])
	local result=$(cat ./countrytable | grep "${vague_word^}")
	if [ -z "$result" ]; then
		cat countrytable | grep "[ $vague_word ]"
		printf "${BITBLIGHT}These may be close to what you want.\033[m\n"
	else
		echo "Not found in table."
	fi
}
#_______________________________________#
isdigit(){
	expr "$1" + 1 > /dev/null 2>&1
	if [ "$?" -ge 2 ]; then
		return 1
	else
		return 0
	fi
}

isnum(){
isdigit "$1"
if [ "$?" -ne 0 ]; then
	local dotcheck=$(echo "$1" | tr -d [:digit:])
	if [ "$dotcheck" = '.' ];then
		return 0
	fi
	return 1
fi
}
#_______________________________________#
GetLatestTable(){
	local table=$(curl -s https://api.exchangeratesapi.io/latest?base=$1)
	if [ -z "$table" ]; then
		exit 2
	else
		echo "$table"
	fi

}


GetRateFromTable(){
	echo $(GetLatestTable "$1" | jq ".rates.$2")
}
#_______________________________________#
RateCalc(){
	local amount="$1"
	local rate="$2"
	echo "scale=12; ("$rate" * "$amount")" | bc
}
#_______________________________________#
OutputResult(){
	local base="$1"
	local target="$2"
	local amount="$3"
	local rate="$4"
	local result="$5"
printf "=======================================\n"
printf " The Exchange was successed! \n" 
printf " Base: ${BITBLIGHT}%.2f\033[m (%s)\n" "$amount" "$base" 
printf " %s   >>   %s \n" "$base" "$target"
printf " Rate : %.2f \n" "$rate" 
printf " Result: ${BITBLIGHT}%.2f\033[m (%s)\n" "$result" "$target" 
printf "=======================================\n"
}
#_______________________________________#

